<?php
/**
 * License Server — Update Package Proxy
 * GET /api/download?token=SIGNED_TOKEN
 *
 * Verifies a short-lived signed token (generated by api/validate.php),
 * then streams the release ZIP from the private GitHub repo.
 * The GitHub PAT and raw license key never reach the client.
 */

require __DIR__ . '/../config.php';
require __DIR__ . '/../bootstrap.php';

$token_raw = trim($_GET['token'] ?? '');

if (!$token_raw) {
    http_response_code(400);
    exit('Missing token.');
}

// ── Verify HMAC signature ─────────────────────────────────
$dot = strrpos($token_raw, '.');
if ($dot === false) {
    http_response_code(403);
    exit('Malformed token.');
}

$payload = substr($token_raw, 0, $dot);
$sig     = substr($token_raw, $dot + 1);

if (!hash_equals(hash_hmac('sha256', $payload, LS_DOWNLOAD_SECRET), $sig)) {
    http_response_code(403);
    exit('Invalid token signature.');
}

// ── Decode and check expiry ───────────────────────────────
$data = json_decode(base64_decode($payload), true);

if (!$data || empty($data['lid']) || empty($data['ver']) || empty($data['exp'])) {
    http_response_code(403);
    exit('Malformed token payload.');
}

if ($data['exp'] < time()) {
    http_response_code(403);
    exit('Download token has expired. Re-check your license to get a fresh link.');
}

$license_id = (int) $data['lid'];
$version    = $data['ver'];

// ── Look up license by ID ─────────────────────────────────
$license = ls_row(
    "SELECT l.*, p.slug AS product_slug FROM licenses l
     JOIN products p ON p.id = l.product_id
     WHERE l.id = :id AND l.status = 'active' LIMIT 1",
    [':id' => $license_id]
);

if (!$license) {
    http_response_code(403);
    exit('License not found or inactive.');
}

if ($license['expires_at'] && strtotime($license['expires_at']) < time()) {
    http_response_code(403);
    exit('License expired.');
}

// ── Look up version (filtered by product) ─────────────────
$ver = ls_row(
    "SELECT * FROM versions WHERE version = :v AND product_id = :pid LIMIT 1",
    [':v' => $version, ':pid' => $license['product_id']]
);

if (!$ver || !$ver['download_url']) {
    http_response_code(404);
    exit('Version not found or no download available.');
}

// ── Fetch from GitHub using PAT ───────────────────────────
if (!defined('LS_GITHUB_TOKEN') || !LS_GITHUB_TOKEN) {
    http_response_code(503);
    exit('Update delivery not configured on the license server.');
}

@set_time_limit(300);

$github_url = $ver['download_url'];

$ctx = stream_context_create([
    'http' => [
        'method'          => 'GET',
        'header'          => implode("\r\n", [
            'Authorization: token ' . LS_GITHUB_TOKEN,
            'Accept: application/vnd.github+json',
            'User-Agent: EvoDesign-LicenseServer/1.0',
            'X-GitHub-Api-Version: 2022-11-28',
        ]),
        'follow_location' => true,
        'max_redirects'   => 5,
        'timeout'         => 120,
    ],
    'ssl' => [
        'verify_peer'      => true,
        'verify_peer_name' => true,
    ],
]);

$handle = @fopen($github_url, 'rb', false, $ctx);

if (!$handle) {
    http_response_code(502);
    exit('Could not fetch update package from source. Check the GitHub token and URL.');
}

// ── Stream ZIP to client ──────────────────────────────────
$product_slug = $license['product_slug'] ?? 'product';
$filename     = $product_slug . '-' . preg_replace('/[^a-z0-9.\-]/i', '', $version) . '.zip';

header('Content-Type: application/zip');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-store, no-cache');
header('X-Robots-Tag: noindex');

fpassthru($handle);
fclose($handle);
exit;
